### Pytorch

is one of the popular deep learning frame work.

In [1]:
import torch 
import torch.nn as nn # For neural network, optimizer, loss function, layers
import torchvision # Computer vision algorithm
import torch.nn.functional as F
import numpy as np 
import matplotlib.pyplot as plt

### Pytorch Tensor

In [2]:
W = [[1, 1, 1],
    [1.5, 1.5, 1.5],
    [2, 2, 2]]

x = [[6], [7], [8]]

b = [[1], [1], [1]]

y = [[0], [0], [0]]

In [4]:
W_np = np.array(W)
W_np

array([[1. , 1. , 1. ],
       [1.5, 1.5, 1.5],
       [2. , 2. , 2. ]])

In [5]:
x_np = np.array(x)
x_np

array([[6],
       [7],
       [8]])

In [6]:
b_np = np.ones((3, 1))
b_np

array([[1.],
       [1.],
       [1.]])

In [11]:
output = np.matmul(W_np, x_np) + b_np
print("Output : \n", output)
print("Shape : ", output.shape)

Output : 
 [[22. ]
 [32.5]
 [43. ]]
Shape :  (3, 1)


### Let's Try Pytorch

In [12]:
W_torch = torch.FloatTensor(W)

x_torch = torch.FloatTensor(x)

b_torch = torch.ones(3,1)


In [13]:
W_torch

tensor([[1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000],
        [2.0000, 2.0000, 2.0000]])

In [14]:
x_torch

tensor([[6.],
        [7.],
        [8.]])

In [15]:
b_torch

tensor([[1.],
        [1.],
        [1.]])

แปลงจาก numpy -> torch : ใช้ฟังก์ชัน torch.FloatTensor()
แปลงจาก torch -> numpy : ใช้ฟังก์ชัน .numpy()

In [16]:
np_array = np.random.random((3,4))
np_array

array([[0.77929447, 0.70250953, 0.2290331 , 0.09632512],
       [0.92809607, 0.20517816, 0.51297797, 0.58676423],
       [0.81849775, 0.16919138, 0.01731616, 0.72209264]])

In [18]:
torch_tensor = torch.FloatTensor(np_array)
torch_tensor

tensor([[0.7793, 0.7025, 0.2290, 0.0963],
        [0.9281, 0.2052, 0.5130, 0.5868],
        [0.8185, 0.1692, 0.0173, 0.7221]])

In [21]:
np_array2 = torch_tensor.numpy()
np_array2

array([[0.7792945 , 0.7025095 , 0.2290331 , 0.09632512],
       [0.92809606, 0.20517816, 0.51297796, 0.5867642 ],
       [0.8184977 , 0.16919138, 0.01731616, 0.7220926 ]], dtype=float32)

### On Pytorch

In [22]:
y = torch.rand(4, 5)
y

tensor([[0.9243, 0.9607, 0.2351, 0.6565, 0.6753],
        [0.0011, 0.6203, 0.4836, 0.9913, 0.3678],
        [0.2462, 0.1082, 0.6233, 0.3738, 0.3785],
        [0.3078, 0.2727, 0.0454, 0.7942, 0.8330]])

In [23]:
y.dim

<function Tensor.dim>

### Tensor Operations

In [48]:
tensor_1 = torch.rand(3,3,3) # first 3 calls batch dimension
tensor_2 = torch.rand(3,3,3)

add_result = tensor_1 + tensor_2
mul_result = tensor_1 * tensor_2

print("Addition : \n", add_result)
print("Batch Multiplication : \n", mul_result)

Addition : 
 tensor([[[0.8059, 0.2810, 1.6030],
         [0.6498, 0.3469, 0.3994],
         [0.8637, 0.8918, 0.5332]],

        [[0.6792, 0.9913, 0.5532],
         [0.5213, 1.4844, 0.9091],
         [0.4740, 0.3805, 1.4839]],

        [[0.9983, 1.8003, 1.1445],
         [1.4798, 1.1546, 0.8958],
         [1.2132, 1.2790, 1.5790]]])
Batch Multiplication : 
 tensor([[[0.0903, 0.0153, 0.6423],
         [0.0779, 0.0298, 0.0397],
         [0.1177, 0.0335, 0.0692]],

        [[0.0862, 0.1492, 0.0730],
         [0.0629, 0.5477, 0.0596],
         [0.0366, 0.0362, 0.5068]],

        [[0.1794, 0.8083, 0.2235],
         [0.4890, 0.2896, 0.1628],
         [0.2708, 0.4024, 0.5907]]])


In [51]:
tensor_3 = torch.rand(2,4,5) # batch dimension = 2
tensor_3

tensor([[[0.7782, 0.4336, 0.2253, 0.5167, 0.0746],
         [0.0390, 0.3217, 0.6172, 0.1016, 0.9457],
         [0.7511, 0.5452, 0.5155, 0.4269, 0.0526],
         [0.4060, 0.1780, 0.0690, 0.8863, 0.5847]],

        [[0.9092, 0.4546, 0.7235, 0.9074, 0.0297],
         [0.8863, 0.1430, 0.6906, 0.2099, 0.3664],
         [0.6866, 0.0023, 0.8448, 0.2105, 0.7837],
         [0.3773, 0.1390, 0.4256, 0.1201, 0.1772]]])

In [52]:
tensor_3.shape

torch.Size([2, 4, 5])

In [54]:
tensor_3.transpose(0,2)

tensor([[[0.7782, 0.9092],
         [0.0390, 0.8863],
         [0.7511, 0.6866],
         [0.4060, 0.3773]],

        [[0.4336, 0.4546],
         [0.3217, 0.1430],
         [0.5452, 0.0023],
         [0.1780, 0.1390]],

        [[0.2253, 0.7235],
         [0.6172, 0.6906],
         [0.5155, 0.8448],
         [0.0690, 0.4256]],

        [[0.5167, 0.9074],
         [0.1016, 0.2099],
         [0.4269, 0.2105],
         [0.8863, 0.1201]],

        [[0.0746, 0.0297],
         [0.9457, 0.3664],
         [0.0526, 0.7837],
         [0.5847, 0.1772]]])

### Indexing

In [62]:
tensor = torch.rand(2,3,1,4)
tensor

tensor([[[[0.5264, 0.8398, 0.5724, 0.2063]],

         [[0.7707, 0.8172, 0.3887, 0.9285]],

         [[0.9636, 0.0340, 0.2442, 0.8884]]],


        [[[0.8564, 0.0429, 0.9501, 0.9965]],

         [[0.6016, 0.5219, 0.0561, 0.0189]],

         [[0.0909, 0.9129, 0.5564, 0.5731]]]])

In [69]:
tensor[-1]

tensor([[[0.8564, 0.0429, 0.9501, 0.9965]],

        [[0.6016, 0.5219, 0.0561, 0.0189]],

        [[0.0909, 0.9129, 0.5564, 0.5731]]])

In [70]:
tensor[0,1]

tensor([[0.7707, 0.8172, 0.3887, 0.9285]])

In [71]:
tensor[:, 1, 0, 2]

tensor([0.3887, 0.0561])

### Describing Tensors

In [75]:
tensor = torch.rand(3,5,3,2)
tensor

tensor([[[[6.8034e-01, 8.0504e-01],
          [4.1067e-01, 4.9003e-01],
          [1.6434e-01, 8.5645e-02]],

         [[6.0689e-01, 2.5349e-01],
          [7.0088e-01, 5.1453e-01],
          [7.8659e-01, 5.8687e-01]],

         [[2.8936e-02, 2.5426e-01],
          [5.7865e-01, 6.8984e-01],
          [4.6971e-01, 2.4007e-01]],

         [[4.4746e-02, 1.8237e-01],
          [9.0218e-01, 7.1670e-01],
          [4.6807e-01, 4.0642e-01]],

         [[3.0626e-01, 2.9710e-01],
          [2.2302e-01, 8.7868e-01],
          [3.4767e-01, 3.6956e-02]]],


        [[[6.7776e-01, 3.5132e-03],
          [6.0318e-01, 8.2254e-01],
          [5.6668e-01, 1.9262e-01]],

         [[5.0710e-01, 5.4635e-01],
          [5.1635e-01, 1.5775e-01],
          [7.9722e-01, 3.3314e-01]],

         [[8.2579e-01, 4.7877e-01],
          [2.7959e-01, 8.7229e-01],
          [9.7527e-01, 5.9596e-01]],

         [[6.9201e-01, 7.3530e-01],
          [1.5530e-01, 4.3205e-01],
          [4.8045e-01, 1.9472e-01]],

        

In [76]:
tensor.shape

torch.Size([3, 5, 3, 2])

In [79]:
tensor.size()

torch.Size([3, 5, 3, 2])

In [80]:
tensor.ndim

4

### Reshape

In [81]:
tensor.reshape(3,30)

tensor([[6.8034e-01, 8.0504e-01, 4.1067e-01, 4.9003e-01, 1.6434e-01, 8.5645e-02,
         6.0689e-01, 2.5349e-01, 7.0088e-01, 5.1453e-01, 7.8659e-01, 5.8687e-01,
         2.8936e-02, 2.5426e-01, 5.7865e-01, 6.8984e-01, 4.6971e-01, 2.4007e-01,
         4.4746e-02, 1.8237e-01, 9.0218e-01, 7.1670e-01, 4.6807e-01, 4.0642e-01,
         3.0626e-01, 2.9710e-01, 2.2302e-01, 8.7868e-01, 3.4767e-01, 3.6956e-02],
        [6.7776e-01, 3.5132e-03, 6.0318e-01, 8.2254e-01, 5.6668e-01, 1.9262e-01,
         5.0710e-01, 5.4635e-01, 5.1635e-01, 1.5775e-01, 7.9722e-01, 3.3314e-01,
         8.2579e-01, 4.7877e-01, 2.7959e-01, 8.7229e-01, 9.7527e-01, 5.9596e-01,
         6.9201e-01, 7.3530e-01, 1.5530e-01, 4.3205e-01, 4.8045e-01, 1.9472e-01,
         1.5349e-01, 3.1850e-01, 7.8572e-01, 9.3548e-01, 8.8346e-01, 3.1527e-01],
        [5.9100e-01, 1.2381e-01, 1.4044e-01, 9.8020e-01, 9.9702e-02, 8.4090e-01,
         8.2833e-01, 6.7481e-01, 1.1790e-04, 7.4206e-01, 6.7786e-01, 7.5066e-01,
         4.8932e-01, 3.752

In [84]:
tensor.flatten() # We can also use the Flatten method to convert to a 1D Tensor

tensor([6.8034e-01, 8.0504e-01, 4.1067e-01, 4.9003e-01, 1.6434e-01, 8.5645e-02,
        6.0689e-01, 2.5349e-01, 7.0088e-01, 5.1453e-01, 7.8659e-01, 5.8687e-01,
        2.8936e-02, 2.5426e-01, 5.7865e-01, 6.8984e-01, 4.6971e-01, 2.4007e-01,
        4.4746e-02, 1.8237e-01, 9.0218e-01, 7.1670e-01, 4.6807e-01, 4.0642e-01,
        3.0626e-01, 2.9710e-01, 2.2302e-01, 8.7868e-01, 3.4767e-01, 3.6956e-02,
        6.7776e-01, 3.5132e-03, 6.0318e-01, 8.2254e-01, 5.6668e-01, 1.9262e-01,
        5.0710e-01, 5.4635e-01, 5.1635e-01, 1.5775e-01, 7.9722e-01, 3.3314e-01,
        8.2579e-01, 4.7877e-01, 2.7959e-01, 8.7229e-01, 9.7527e-01, 5.9596e-01,
        6.9201e-01, 7.3530e-01, 1.5530e-01, 4.3205e-01, 4.8045e-01, 1.9472e-01,
        1.5349e-01, 3.1850e-01, 7.8572e-01, 9.3548e-01, 8.8346e-01, 3.1527e-01,
        5.9100e-01, 1.2381e-01, 1.4044e-01, 9.8020e-01, 9.9702e-02, 8.4090e-01,
        8.2833e-01, 6.7481e-01, 1.1790e-04, 7.4206e-01, 6.7786e-01, 7.5066e-01,
        4.8932e-01, 3.7523e-01, 3.2430e-

In [85]:
tensor.numel() # View the number of elements in total

90

In [86]:
tensor.ndim

4

### Squeezing and Unsqueezing

In [87]:
tensor = torch.rand(3, 2)

tensor.shape

torch.Size([3, 2])

In [89]:
tensor.unsqueeze # Unsqueeze adds an "empty" dimension to our Tensor

<function Tensor.unsqueeze>

In [91]:
tensor.unsqueeze(1).shape # Unsqueeze adds an "empty" dimension to pur Tensor

torch.Size([3, 1, 2])

In [98]:
### Lets create a 2D Tensor
tensor = torch.rand(3,2)
tensor

tensor([[0.0026, 0.5746],
        [0.6956, 0.9142],
        [0.3225, 0.3260]])

In [99]:
tensor.shape

torch.Size([3, 2])

In [100]:
tensor.unsqueeze(2).shape

torch.Size([3, 2, 1])

In [101]:
tensor.unsqueeze(1).shape

torch.Size([3, 1, 2])

In [125]:
# Lets create a 4D Tensor with a few "empty" dimensions
tensor = torch.rand(1,3,1,2)
tensor

tensor([[[[0.6362, 0.1437]],

         [[0.1600, 0.0260]],

         [[0.1854, 0.5706]]]])

In [126]:
tensor.squeeze(2).shape # squeeze removes an "empty" dimension from our Tensor

torch.Size([1, 3, 2])

In [127]:
tensor.squeeze(0).shape # squeeze removes an "empty" dimension from our Tensor

torch.Size([3, 1, 2])

In [128]:
tensor.squeeze().shape # If we don't specify a dimension, squeeze will remove ALL empty dimensions

torch.Size([3, 2])

### Boardcasting

In [129]:
tensor1 = torch.rand(1,4,3,1)
tensor2 = torch.rand(3,4,1,4)

tensor3 = tensor1 + tensor2

In [130]:
tensor1.shape

torch.Size([1, 4, 3, 1])

In [131]:
tensor2.shape

torch.Size([3, 4, 1, 4])

In [132]:
tensor3.shape

torch.Size([3, 4, 3, 4])

### Pytorch Autograd