In [378]:
import pandas as pd 

In [379]:
df = pd.read_csv("C:/Users/araya/Desktop/vscode/Deep-learning-coding/opencv/coords1.csv")
df

class        x1        y1        z1        v1        x2        y2  \
0     กฎกระทรวง  0.501350  0.245246 -1.216694  0.999879  0.530310  0.205005   
1     กฎกระทรวง  0.499739  0.248179 -1.469002  0.999858  0.530218  0.206910   
2     กฎกระทรวง  0.498399  0.249974 -1.485348  0.999838  0.530082  0.208149   
3     กฎกระทรวง  0.497180  0.251227 -1.499438  0.999819  0.529854  0.209062   
4     กฎกระทรวง  0.496315  0.252170 -1.486249  0.999796  0.529665  0.209846   
..          ...       ...       ...       ...       ...       ...       ...   
825        กรรม  0.506491  0.270052 -1.498700  0.999911  0.539074  0.225080   
826        กรรม  0.507932  0.269298 -1.499939  0.999907  0.540079  0.224516   
827        กรรม  0.509001  0.268810 -1.493553  0.999905  0.540894  0.224151   
828        กรรม  0.509209  0.268344 -1.451792  0.999901  0.541108  0.223779   
829  กรรมสิทธิ์  0.488281  0.240215 -1.102423  0.999894  0.516165  0.202690   

           z2        v2        x3  ...      z499  v499      x500      y500  \
0   -1.145553  0.999764  0.546866  ... -0.006467     0  0.561279  0.222134   
1   -1.396843  0.999728  0.546835  ... -0.006111     0  0.560142  0.221125   
2   -1.412991  0.999695  0.546782  ... -0.005613     0  0.560375  0.221490   
3   -1.427445  0.999664  0.546684  ... -0.005617     0  0.560382  0.221574   
4   -1.414363  0.999627  0.546596  ... -0.005550     0  0.560116  0.221396   
..        ...       ...       ...  ...       ...   ...       ...       ...   
825 -1.423538  0.999818  0.552871  ... -0.007212     0  0.572845  0.237749   
826 -1.424863  0.999813  0.553801  ... -0.007057     0  0.573102  0.237343   
827 -1.418817  0.999811  0.554646  ... -0.006981     0  0.573372  0.236941   
828 -1.379970  0.999806  0.554853  ... -0.006843     0  0.573709  0.236540   
829 -1.033309  0.999756  0.530555  ... -0.007970     0  0.543537  0.216119   

         z500  v500      x501      y501      z501  v501  
0    0.009669     0  0.566310  0.218836  0.009777     0  
1    0.010467     0  0.565165  0.218090  0.010578     0  
2    0.011074     0  0.565401  0.218464  0.011207     0  
3    0.010852     0  0.565431  0.218495  0.010977     0  
4    0.010952     0  0.565149  0.218365  0.011072     0  
..        ...   ...       ...       ...       ...   ...  
825  0.011139     0  0.577666  0.235406  0.011277     0  
826  0.011397     0  0.577956  0.234940  0.011539     0  
827  0.011489     0  0.578216  0.234574  0.011631     0  
828  0.011481     0  0.578612  0.234107  0.011619     0  
829  0.007955     0  0.548205  0.213184  0.008077     0  

[830 rows x 2005 columns]

In [380]:
for idx, values in enumerate(df):
    if idx == 501:
        break
    df = df.drop("v"+str(idx+1), axis=1)
    idx = int(idx)


In [381]:
df

class        x1        y1        z1        x2        y2        z2  \
0     กฎกระทรวง  0.501350  0.245246 -1.216694  0.530310  0.205005 -1.145553   
1     กฎกระทรวง  0.499739  0.248179 -1.469002  0.530218  0.206910 -1.396843   
2     กฎกระทรวง  0.498399  0.249974 -1.485348  0.530082  0.208149 -1.412991   
3     กฎกระทรวง  0.497180  0.251227 -1.499438  0.529854  0.209062 -1.427445   
4     กฎกระทรวง  0.496315  0.252170 -1.486249  0.529665  0.209846 -1.414363   
..          ...       ...       ...       ...       ...       ...       ...   
825        กรรม  0.506491  0.270052 -1.498700  0.539074  0.225080 -1.423538   
826        กรรม  0.507932  0.269298 -1.499939  0.540079  0.224516 -1.424863   
827        กรรม  0.509001  0.268810 -1.493553  0.540894  0.224151 -1.418817   
828        กรรม  0.509209  0.268344 -1.451792  0.541108  0.223779 -1.379970   
829  กรรมสิทธิ์  0.488281  0.240215 -1.102423  0.516165  0.202690 -1.033309   

           x3        y3        z3  ...      z498      x499      y499  \
0    0.546866  0.205347 -1.145928  ...  0.000092  0.510696  0.228523   
1    0.546835  0.207374 -1.397385  ...  0.000588  0.509520  0.228623   
2    0.546782  0.208686 -1.413539  ...  0.001101  0.509984  0.228753   
3    0.546684  0.209634 -1.427985  ...  0.001089  0.509727  0.228813   
4    0.546596  0.210447 -1.414894  ...  0.001168  0.509471  0.228746   
..        ...       ...       ...  ...       ...       ...       ...   
825  0.552871  0.225831 -1.424037  ... -0.000232  0.522136  0.244177   
826  0.553801  0.225343 -1.425340  ... -0.000064  0.522395  0.243677   
827  0.554646  0.225023 -1.419323  ...  0.000013  0.522742  0.243205   
828  0.554853  0.224662 -1.380399  ...  0.000166  0.522908  0.242615   
829  0.530555  0.203328 -1.033579  ... -0.001624  0.494835  0.222671   

         z499      x500      y500      z500      x501      y501      z501  
0   -0.006467  0.561279  0.222134  0.009669  0.566310  0.218836  0.009777  
1   -0.006111  0.560142  0.221125  0.010467  0.565165  0.218090  0.010578  
2   -0.005613  0.560375  0.221490  0.011074  0.565401  0.218464  0.011207  
3   -0.005617  0.560382  0.221574  0.010852  0.565431  0.218495  0.010977  
4   -0.005550  0.560116  0.221396  0.010952  0.565149  0.218365  0.011072  
..        ...       ...       ...       ...       ...       ...       ...  
825 -0.007212  0.572845  0.237749  0.011139  0.577666  0.235406  0.011277  
826 -0.007057  0.573102  0.237343  0.011397  0.577956  0.234940  0.011539  
827 -0.006981  0.573372  0.236941  0.011489  0.578216  0.234574  0.011631  
828 -0.006843  0.573709  0.236540  0.011481  0.578612  0.234107  0.011619  
829 -0.007970  0.543537  0.216119  0.007955  0.548205  0.213184  0.008077  

[830 rows x 1504 columns]

In [382]:
X = []

In [383]:
import numpy as np

In [384]:
X1 = df.values[0:142,1:]
X1

array([[0.501349568, 0.245245695, -1.216694236, ..., 0.56630969,
        0.218836069, 0.009776841],
       [0.499739289, 0.248178989, -1.469002008, ..., 0.565164566,
        0.218090415, 0.010577686],
       [0.498399287, 0.249973699, -1.485347509, ..., 0.565400541,
        0.218464151, 0.011207255],
       ...,
       [0.486114353, 0.251273662, -1.341647148, ..., 0.557196379,
        0.217676103, 0.009148243],
       [0.487307936, 0.251391917, -1.357400298, ..., 0.557516456,
        0.217173994, 0.009745215],
       [0.488320261, 0.251569331, -1.357887387, ..., 0.557722867,
        0.217023194, 0.010076373]], dtype=object)

In [385]:
X2 = df.values[142:276,1:]
X2

array([[0.492212027, 0.238237515, -1.284981489, ..., 0.557813644,
        0.212378561, 0.00941062],
       [0.491994888, 0.240470842, -1.428828359, ..., 0.557141602,
        0.21162726, 0.009867254],
       [0.492001444, 0.240891233, -1.409263611, ..., 0.556691587,
        0.212160736, 0.009759822],
       ...,
       [0.481416523, 0.226043299, -1.331809878, ..., 0.550316811,
        0.192333877, 0.012298049],
       [0.481473029, 0.225693658, -1.335124731, ..., 0.550251842,
        0.192142352, 0.01222215],
       [0.481493026, 0.225462675, -1.349697232, ..., 0.550148308,
        0.191874638, 0.012380698]], dtype=object)

In [386]:
X3 = df.values[276:362,1:]
X3

array([[0.509979427, 0.227209851, -1.330497026, ..., 0.574683666,
        0.201673225, 0.012432273],
       [0.509981155, 0.230530143, -1.4289428, ..., 0.573323369,
        0.20164901, 0.012064613],
       [0.509979486, 0.233348414, -1.476526499, ..., 0.5731318,
        0.201880246, 0.012798474],
       ...,
       [0.502632141, 0.224639609, -1.327178478, ..., 0.56796217,
        0.194047898, 0.015527265],
       [0.502725184, 0.223328531, -1.342507958, ..., 0.567143857,
        0.193101436, 0.015961634],
       [0.502746165, 0.222521827, -1.313816547, ..., 0.566207767,
        0.192000225, 0.016169909]], dtype=object)

In [387]:
X4 = df.values[362:451,1:]
X5 = df.values[451:578,1:]
X6 = df.values[578:729,1:]
X7 = df.values[729:829,1:]

In [388]:
X = [X1,X2,X3,X4,X5,X6,X7]
X

[array([[0.501349568, 0.245245695, -1.216694236, ..., 0.56630969,
         0.218836069, 0.009776841],
        [0.499739289, 0.248178989, -1.469002008, ..., 0.565164566,
         0.218090415, 0.010577686],
        [0.498399287, 0.249973699, -1.485347509, ..., 0.565400541,
         0.218464151, 0.011207255],
        ...,
        [0.486114353, 0.251273662, -1.341647148, ..., 0.557196379,
         0.217676103, 0.009148243],
        [0.487307936, 0.251391917, -1.357400298, ..., 0.557516456,
         0.217173994, 0.009745215],
        [0.488320261, 0.251569331, -1.357887387, ..., 0.557722867,
         0.217023194, 0.010076373]], dtype=object),
 array([[0.492212027, 0.238237515, -1.284981489, ..., 0.557813644,
         0.212378561, 0.00941062],
        [0.491994888, 0.240470842, -1.428828359, ..., 0.557141602,
         0.21162726, 0.009867254],
        [0.492001444, 0.240891233, -1.409263611, ..., 0.556691587,
         0.212160736, 0.009759822],
        ...,
        [0.481416523, 0.226043299,

In [389]:
X[0]

array([[0.501349568, 0.245245695, -1.216694236, ..., 0.56630969,
        0.218836069, 0.009776841],
       [0.499739289, 0.248178989, -1.469002008, ..., 0.565164566,
        0.218090415, 0.010577686],
       [0.498399287, 0.249973699, -1.485347509, ..., 0.565400541,
        0.218464151, 0.011207255],
       ...,
       [0.486114353, 0.251273662, -1.341647148, ..., 0.557196379,
        0.217676103, 0.009148243],
       [0.487307936, 0.251391917, -1.357400298, ..., 0.557516456,
        0.217173994, 0.009745215],
       [0.488320261, 0.251569331, -1.357887387, ..., 0.557722867,
        0.217023194, 0.010076373]], dtype=object)

In [390]:
y = ["กฎกระทรวง","กฎหมายรัฐธรรมนูญ","กด (ท่าที่1)","กทปส","กรณ์ จาติกวณิช","กรมอนามัย","กรรม"]
y

['กฎกระทรวง',
 'กฎหมายรัฐธรรมนูญ',
 'กด (ท่าที่1)',
 'กทปส',
 'กรณ์ จาติกวณิช',
 'กรมอนามัย',
 'กรรม']

In [421]:
for i in range(len(y)):
    print(y[i])
    # print(X[i])

กฎกระทรวง
กฎหมายรัฐธรรมนูญ
กด (ท่าที่1)
กทปส
กรณ์ จาติกวณิช
กรมอนามัย
กรรม


In [436]:
Dict = {y[0]:X[0], y[1]:X[1], y[2]:X[2], y[3]:X[3], y[4]:X[4], y[5]:X[5], y[6]:X[6]}
Dict

{'กฎกระทรวง': array([[0.501349568, 0.245245695, -1.216694236, ..., 0.56630969,
         0.218836069, 0.009776841],
        [0.499739289, 0.248178989, -1.469002008, ..., 0.565164566,
         0.218090415, 0.010577686],
        [0.498399287, 0.249973699, -1.485347509, ..., 0.565400541,
         0.218464151, 0.011207255],
        ...,
        [0.486114353, 0.251273662, -1.341647148, ..., 0.557196379,
         0.217676103, 0.009148243],
        [0.487307936, 0.251391917, -1.357400298, ..., 0.557516456,
         0.217173994, 0.009745215],
        [0.488320261, 0.251569331, -1.357887387, ..., 0.557722867,
         0.217023194, 0.010076373]], dtype=object),
 'กฎหมายรัฐธรรมนูญ': array([[0.492212027, 0.238237515, -1.284981489, ..., 0.557813644,
         0.212378561, 0.00941062],
        [0.491994888, 0.240470842, -1.428828359, ..., 0.557141602,
         0.21162726, 0.009867254],
        [0.492001444, 0.240891233, -1.409263611, ..., 0.556691587,
         0.212160736, 0.009759822],
        ...,
 

In [393]:
# A = [1,2,3]
# B = [4,5]
# A = np.array(A)
# B = np.array(B)
# B

In [394]:
# [A,B]

### Train-Test-Spilt

In [406]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20)

In [407]:
len(X_train), len(X_test)

(4, 3)

In [439]:
X_train[0]

array([[0.504905999, 0.23709847, -1.21154058, ..., 0.564275503,
        0.208181038, 0.008794018],
       [0.504457653, 0.238124266, -1.189621568, ..., 0.564340651,
        0.208140343, 0.008453688],
       [0.504143238, 0.238475472, -1.191511989, ..., 0.564252615,
        0.20802255, 0.008863508],
       ...,
       [0.496290386, 0.230650678, -1.309617281, ..., 0.562429428,
        0.204313576, 0.01273088],
       [0.496520579, 0.230838552, -1.308454871, ..., 0.562454104,
        0.204459548, 0.012589185],
       [0.497197717, 0.231167197, -1.305349588, ..., 0.563348174,
        0.204465687, 0.012800346]], dtype=object)

### Model

In [437]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(hidden_layer_sizes=(50), max_iter=2000, random_state=1)
model.fit(X_train, y_train)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.