In [552]:
import pandas as pd 

In [ ]:
df = pd.read_csv("C:/Users/araya/Desktop/vscode/Deep-learning-coding/opencv/coords1.csv")
df

In [554]:
for idx, values in enumerate(df):
    if idx == 501:
        break
    df = df.drop("v"+str(idx+1), axis=1)
    idx = int(idx)


In [ ]:
df

In [ ]:
df.values

In [557]:
X = []
y = []

In [ ]:
# Get the rows where the current "class" value is different from the previous one
unique_classes = df["class"] != df["class"].shift(1)

# Print and append the unique values
for value in df.loc[unique_classes, "class"]:
    print(value)
    y.append(value)

In [ ]:
y

In [ ]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()

y = le.fit_transform(y)
y

In [561]:
import numpy as np

In [ ]:
X1 = df.values[0:142,1:]
X1

In [ ]:
X2 = df.values[142:276,1:]
X2

In [ ]:
X3 = df.values[276:362,1:]
X3

In [565]:
X4 = df.values[362:451,1:]
X5 = df.values[451:578,1:]
X6 = df.values[578:729,1:]
X7 = df.values[729:829,1:]
X8 = df.values[829:830,1:]

In [ ]:
X = np.asarray([X1,X2,X3,X4,X5,X6,X7,X8],dtype=object)
X

In [ ]:
X[0]

In [ ]:
data = [{y[0]:X[0]}, {y[1]:X[1]}, {y[2]:X[2]}, {y[3]:X[3]}, {y[4]:X[4]}, {y[5]:X[5]}, {y[6]:X[6]}]
data

In [572]:
import torch 
import torch.nn as nn

In [573]:
# A = [1,2,3]
# B = [4,5]
# A = np.array(A)
# B = np.array(B)
# B

In [574]:
# [A,B]

### Train-Test-Spilt

In [575]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20)

In [ ]:
len(X_train), len(X_test)

In [ ]:
X_train

In [ ]:
X_train[0].shape

In [ ]:
X_train

In [ ]:
y_train

### Model

In [ ]:
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, LSTM, Dense

model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(timesteps, num_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(100))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32)


In [ ]:
np.__version__

In [612]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, LSTM, Dense
from keras.utils import to_categorical, pad_sequences

# Load data
df = pd.read_csv("C:/Users/araya/Desktop/vscode/Deep-learning-coding/opencv/coords1.csv")

# Drop columns named 'v1', 'v2', ..., 'v501'
for idx in range(501):
    column_name = "v" + str(idx + 1)
    if column_name in df.columns:
        df = df.drop(column_name, axis=1)

# Extract unique class labels
unique_classes = df["class"] != df["class"].shift(1)
y = df.loc[unique_classes, "class"].values

# Encode class labels
le = LabelEncoder()
y = le.fit_transform(y)

# Split the data into input segments (manually sliced)
X1 = df.values[0:142, 1:]
X2 = df.values[142:276, 1:]
X3 = df.values[276:362, 1:]
X4 = df.values[362:451, 1:]
X5 = df.values[451:578, 1:]
X6 = df.values[578:729, 1:]
X7 = df.values[729:829, 1:]
X8 = df.values[829:830, 1:]

# Stack inputs as a list (keeping them as sequences for now)
X = [X1, X2, X3, X4, X5, X6, X7, X8]

# Pad sequences so they all have the same length
X = pad_sequences(X, padding='post', dtype='float32')

# Determine number of classes
num_classes = len(np.unique(y))

# One-hot encode labels
y = to_categorical(y, num_classes)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20)

# Define the model (set timesteps and num_features based on your data)
timesteps = X_train.shape[1]  # Length of the padded sequences
num_features = X_train.shape[2]  # Number of features per timestep

model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(timesteps, num_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(100))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)


Epoch 1/10


c:\Users\araya\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.0000e+00 - loss: 2.0721
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.2000 - loss: 1.9513
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.2000 - loss: 1.8365
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.2000 - loss: 1.7408
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4000 - loss: 1.6745
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.4000 - loss: 1.6219
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4000 - loss: 1.5841
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4000 - loss: 1.5403
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4000 - loss: 1.4937
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.4000 - loss: 1.4396


In [620]:
# Predict on the test data
y_pred = model.predict(X_test)

# Convert predictions from probabilities to class labels
y_pred_classes = np.argmax(y_pred, axis=1)

# Convert test labels to class labels (from one-hot encoding)
y_test_classes = np.argmax(y_test, axis=1)

# Evaluate the model
from sklearn.metrics import accuracy_score, classification_report

# Calculate accuracy
accuracy = accuracy_score(y_test_classes, y_pred_classes)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Print a classification report
print(classification_report(y_test_classes, y_pred_classes))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Accuracy: 0.00%
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           1       0.00      0.00      0.00       0.0
           2       0.00      0.00      0.00       0.0
           4       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       1.0
           7       0.00      0.00      0.00       1.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



c:\Users\araya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\araya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\araya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

In [621]:
y_pred_classes

array([4, 2, 1], dtype=int64)

In [622]:
timesteps

151

In [623]:
y_test

array([[0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0.]])

In [617]:
y_train

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])