In [742]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp 

In [743]:
mp_holist = mp.solutions.holistic 
mp_draw = mp.solutions.drawing_utils

In [744]:
def mediapipe_detection(img, model):
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img.flags.writeable = False                 
    result = model.process(img)                 # Make prediction
    img.flags.writeable = True                   
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR) 
    return img, result

In [745]:
def draw_landmarks(img, result):
    mp_draw.draw_landmarks(img, result.face_landmarks, mp_holist.FACEMESH_CONTOURS) # Draw face connections
    mp_draw.draw_landmarks(img, result.pose_landmarks, mp_holist.POSE_CONNECTIONS) # Draw pose connections
    mp_draw.draw_landmarks(img, result.left_hand_landmarks, mp_holist.HAND_CONNECTIONS) # Draw left hand connections
    mp_draw.draw_landmarks(img, result.right_hand_landmarks, mp_holist.HAND_CONNECTIONS) # Draw right hand connections

In [746]:
def draw_styled_landmarks(img, result):
    mp_draw.draw_landmarks(img, result.face_landmarks, mp_holist.FACEMESH_CONTOURS, 
                             mp_draw.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), # color the joint 
                             mp_draw.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1) #color the connection
                             ) 
    # mp_draw.draw_landmarks(img, result.face_landmarks, mp_holist.FACEMESH_CONTOURS, 
    #                          mp_draw.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), # color the joint 
    #                          mp_draw.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1) #color the connection
    #                          ) 
    
    mp_draw.draw_landmarks(img, result.pose_landmarks, mp_holist.POSE_CONNECTIONS,
                             mp_draw.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
                             mp_draw.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             ) 
    mp_draw.draw_landmarks(img, result.left_hand_landmarks, mp_holist.HAND_CONNECTIONS, 
                             mp_draw.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_draw.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    mp_draw.draw_landmarks(img, result.right_hand_landmarks, mp_holist.HAND_CONNECTIONS, 
                             mp_draw.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_draw.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 

In [ ]:
mp_holist.POSE_CONNECTIONS

In [ ]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holist.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        ret, frame = cap.read()

        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        draw_styled_landmarks(image, results)

        cv2.imshow('OpenCV Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

In [749]:
cap.release()
cv2.destroyAllWindows()

In [ ]:
results.pose_landmarks.landmark[0].visibility

In [ ]:
len(results.pose_landmarks.landmark)

In [752]:
def extract_keypoints(results):
    pose=np.array([[res.x,res.y,res.z,res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    left_hnd=np.array([[res.x,res.y,res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    right_hnd=np.array([[res.x,res.y,res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    face=np.array([[res.x,res.y,res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    return np.concatenate([pose,left_hnd,right_hnd,face])
# concatenating for the model to detect the sign language

In [ ]:
extract_keypoints(results).shape

In [797]:
import os 
video_dir = "C:/Users/araya/Desktop/keypoints/video_extract"
video_list = []
video_list = os.listdir(video_dir)

len(video_list)

62

In [798]:
video_list

['กฎกระทรวง.mp4',
 'กฎหมายรัฐธรรมนูญ.mp4',
 'กรมอนามัย.mp4',
 'กรรม.mp4',
 'กรรมสิทธิ์.mp4',
 'กระโดด.mp4',
 'กลับ.mp4',
 'กล้วยบวชชี.mp4',
 'กล้วยเชื่อม.mp4',
 'ข้าวพันผัก.mp4',
 'ตลาดหัวดง.mp4',
 'นก.mp4',
 'น้อง.mp4',
 'บัวลอยน้ำขัง.mp4',
 'เขิน.mp4',
 'เคย.mp4',
 'เจอ.mp4',
 'เจ้าหนี้.mp4',
 'เช่าซื้อ.mp4',
 'เดิน.mp4',
 'เดิมพัน.mp4',
 'เนื้อวัว.mp4',
 'เนื้อหมู.mp4',
 'เปรู.mp4',
 'เพนกวิน.mp4',
 'เพลีย.mp4',
 'เมื่อย.mp4',
 'เรียก.mp4',
 'เรือข้ามฟาก.mp4',
 'เร่งมือ.mp4',
 'เล็ก.mp4',
 'เวอร์ไป.mp4',
 'เวเนซุเอลา.mp4',
 'เศรษฐกิจ.mp4',
 'เสรีภาพ.mp4',
 'เสือก.mp4',
 'เส้น.mp4',
 'เหตุสุดวิสัย.mp4',
 'เห็นด้วย.mp4',
 'เฮโรอีน.mp4',
 'แท็บเล็ต.mp4',
 'แบก.mp4',
 'แผนที่.mp4',
 'แม่ลาว (อำเภอ).mp4',
 'แม่วงก์ (อำเภอ).mp4',
 'แหวน.mp4',
 'แองโกลา.mp4',
 'แอฟริกาใต้.mp4',
 'แอลจีเรีย.mp4',
 'แอลเบเนีย.mp4',
 'โกหก.mp4',
 'โจทก์.mp4',
 'โชจู.mp4',
 'โนโหวต.mp4',
 'โบ๊เบ๊.mp4',
 'โรงงานทำ.mp4',
 'โรมาเนีย.mp4',
 'ใหญ่.mp4',
 'ไดโนเสาร์.mp4',
 'ไถ่ถอน.mp4',
 'ไนกี้.mp4',
 'ไอซ์.mp4']

In [799]:
# Path for exported data, numpy arrays
Model_Data=os.path.join('Data for different actions')

actions = np.array(video_list)

no_of_seqs = 1

# 30 frames in length
seq_length = 30

In [ ]:
actions

In [758]:
# just creating the folders and sub folders

for action in actions: 
    try: 
        os.makedirs(os.path.join(Model_Data, action))
    except:
        pass

Collecting keypoint values for Training nd Testing

In [800]:
# Define the directory where your videos are stored
directory = "C:/Users/araya/Desktop/keypoints/video_extract"

In [801]:
directory

'C:/Users/araya/Desktop/keypoints/video_extract'

In [802]:
for filename in actions:
    print(directory + '/' + filename)

C:/Users/araya/Desktop/keypoints/video_extract/กฎกระทรวง.mp4
C:/Users/araya/Desktop/keypoints/video_extract/กฎหมายรัฐธรรมนูญ.mp4
C:/Users/araya/Desktop/keypoints/video_extract/กรมอนามัย.mp4
C:/Users/araya/Desktop/keypoints/video_extract/กรรม.mp4
C:/Users/araya/Desktop/keypoints/video_extract/กรรมสิทธิ์.mp4
C:/Users/araya/Desktop/keypoints/video_extract/กระโดด.mp4
C:/Users/araya/Desktop/keypoints/video_extract/กลับ.mp4
C:/Users/araya/Desktop/keypoints/video_extract/กล้วยบวชชี.mp4
C:/Users/araya/Desktop/keypoints/video_extract/กล้วยเชื่อม.mp4
C:/Users/araya/Desktop/keypoints/video_extract/ข้าวพันผัก.mp4
C:/Users/araya/Desktop/keypoints/video_extract/ตลาดหัวดง.mp4
C:/Users/araya/Desktop/keypoints/video_extract/นก.mp4
C:/Users/araya/Desktop/keypoints/video_extract/น้อง.mp4
C:/Users/araya/Desktop/keypoints/video_extract/บัวลอยน้ำขัง.mp4
C:/Users/araya/Desktop/keypoints/video_extract/เขิน.mp4
C:/Users/araya/Desktop/keypoints/video_extract/เคย.mp4
C:/Users/araya/Desktop/keypoints/video_extrac

In [ ]:
# Set mediapipe model 
for action in actions:
    video_path = os.path.join("C:/Users/araya/Desktop/keypoints/video_extract", action)
    cap = cv2.VideoCapture(video_path)
    cap.set(cv2.CAP_PROP_FPS, 60)
    length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    print("LENGTH:" + str(length))

    if not cap.isOpened():
        print(f"Error opening video file: {video_path}")
        continue

    with mp_holist.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
        for seq in range(no_of_seqs):
            for frame_num in range(seq_length):

                ret, frame = cap.read()
                if not ret:
                    print(f"End of video {video_path}")
                    break
                
                img, results = mediapipe_detection(frame, holistic)
                draw_styled_landmarks(img, results)

                # print(frame_num)

                if frame_num == 0: 
                    cv2.putText(img, 'DATA COLLECTION STARTED', (120,200), 
                                cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(img, f'Collecting frames for - {action} Sequence Number - {seq}', (15,12), 
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    cv2.imshow('OpenCV Window', img)
                    cv2.waitKey(2000)  # 2 seconds delay for setup
                else: 
                    cv2.putText(img, f'Collecting frames for - {action} Sequence Number - {seq}', (15,12), 
                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    cv2.imshow('OpenCV Window', img)

                keypoints = extract_keypoints(results)
                npy_path = os.path.join(Model_Data, action, f"frame_{frame_num}.npy")
                os.makedirs(os.path.dirname(npy_path), exist_ok=True)
                np.save(npy_path, keypoints)

                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break

            if not ret:
                break

    cap.release()
    cv2.destroyAllWindows()

In [763]:
# # Set mediapipe model 
# for action in actions:
#     video_path = os.path.join(video_dir, action)
#     cap = cv2.VideoCapture(video_path)

#     if not cap.isOpened():
#         print(f"Error opening video file: {video_path}")
#         continue

#     with mp_holist.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
#         frames = []

#         while True:
#             ret, frame = cap.read()
#             if not ret:
#                 break
            
#             img, results = mediapipe_detection(frame, holistic)
#             keypoints = extract_keypoints(results)
#             frames.append(keypoints)

#         # Padding or trimming to fixed sequence length
#         if len(frames) < seq_length:
#             padding = [np.zeros_like(frames[0]) for _ in range(seq_length - len(frames))]
#             frames.extend(padding)
#         else:
#             frames = frames[:seq_length]

#         # Save sequences
#         for i in range(len(frames)):
#             npy_path = os.path.join(Model_Data, action, f"frame_{i}.npy")
#             np.save(npy_path, frames[i])

#     cap.release()

# cv2.destroyAllWindows()

In [764]:
# # Loop through all files in the directory
# for filename in os.listdir(directory):
#     # Check if the file is a video by checking its extension
#     if filename.endswith(('.mp4', '.avi', '.mkv', '.mov')):
#         print(f"Processing {filename}...")
#         video_path = os.path.join(directory, filename)

#         class_name = os.path.splitext(os.path.basename(video_path))[0]
        
#         cap = cv2.VideoCapture(video_path)
#         with mp_holist.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
#             for action in actions:
#                 for seq in range(no_of_seqs):
#                     for frame_num in range(seq_length):
#                         ret, frame = cap.read()
#                         if not ret:
#                             print("Error: Failed to read frame.")
#                             break  # Exit the loop if frame read fails
                        
#                         img, results = mediapipe_detection(frame, holistic)
#                         draw_styled_landmarks(img, results)

#                         # logic is for the formatting portion
#                         if frame_num == 0: 
#                             cv2.putText(img, 'DATA COLLECTION STARTED', (120,200), 
#                                     cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
#                             cv2.putText(img, 'Collecting frames for - {} and Sequence Number - {}'.format(action, seq), (15,12), 
#                                     cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
#                             # Show to screen
#                             cv2.imshow('OpenCV Window', img)
#                             # providing the break for adjusting the posture
#                             cv2.waitKey(2000) # 2 sec
#                         else: 
#                             cv2.putText(img, 'Collecting frames for - {} and Sequence Number - {}'.format(action, seq), (15,12), 
#                                     cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
#                             # Show to screen
#                             cv2.imshow('OpenCV Window', img)

#                         keypoints = extract_keypoints(results)
#                         npy_path = os.path.join(Model_Data, action, str(seq), str(frame_num))
#                         np.save(npy_path, keypoints)

#                         if cv2.waitKey(10) & 0xFF == ord('q'):
#                             break

#         cap.release()
#         cv2.destroyAllWindows()


In [765]:
cap.release()
cv2.destroyAllWindows()

In [803]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

In [804]:
labelMap = {label:num for num, label in enumerate(actions)}

In [805]:
labelMap

{'กฎกระทรวง.mp4': 0,
 'กฎหมายรัฐธรรมนูญ.mp4': 1,
 'กรมอนามัย.mp4': 2,
 'กรรม.mp4': 3,
 'กรรมสิทธิ์.mp4': 4,
 'กระโดด.mp4': 5,
 'กลับ.mp4': 6,
 'กล้วยบวชชี.mp4': 7,
 'กล้วยเชื่อม.mp4': 8,
 'ข้าวพันผัก.mp4': 9,
 'ตลาดหัวดง.mp4': 10,
 'นก.mp4': 11,
 'น้อง.mp4': 12,
 'บัวลอยน้ำขัง.mp4': 13,
 'เขิน.mp4': 14,
 'เคย.mp4': 15,
 'เจอ.mp4': 16,
 'เจ้าหนี้.mp4': 17,
 'เช่าซื้อ.mp4': 18,
 'เดิน.mp4': 19,
 'เดิมพัน.mp4': 20,
 'เนื้อวัว.mp4': 21,
 'เนื้อหมู.mp4': 22,
 'เปรู.mp4': 23,
 'เพนกวิน.mp4': 24,
 'เพลีย.mp4': 25,
 'เมื่อย.mp4': 26,
 'เรียก.mp4': 27,
 'เรือข้ามฟาก.mp4': 28,
 'เร่งมือ.mp4': 29,
 'เล็ก.mp4': 30,
 'เวอร์ไป.mp4': 31,
 'เวเนซุเอลา.mp4': 32,
 'เศรษฐกิจ.mp4': 33,
 'เสรีภาพ.mp4': 34,
 'เสือก.mp4': 35,
 'เส้น.mp4': 36,
 'เหตุสุดวิสัย.mp4': 37,
 'เห็นด้วย.mp4': 38,
 'เฮโรอีน.mp4': 39,
 'แท็บเล็ต.mp4': 40,
 'แบก.mp4': 41,
 'แผนที่.mp4': 42,
 'แม่ลาว (อำเภอ).mp4': 43,
 'แม่วงก์ (อำเภอ).mp4': 44,
 'แหวน.mp4': 45,
 'แองโกลา.mp4': 46,
 'แอฟริกาใต้.mp4': 47,
 'แอลจีเรีย.mp4': 48,
 'แอลเบเนีย

In [806]:
seqs, labels = [], []

for action in actions:
    for seq in range(no_of_seqs):
        window = []
        for frame_num in range(seq_length):
            res = np.load(os.path.join(Model_Data, action, f"frame_{frame_num}.npy")) 
            window.append(res)
        seqs.append(window)

        labels.append(labelMap[action])

In [807]:
import numpy as np 
import os
Model_Data=os.path.join('Data for different actions')
action = "กฎกระทรวง.mp4"
a = np.load(os.path.join(Model_Data, action, "frame_0.npy"))
a

array([ 0.50134957,  0.2452457 , -1.21669424, ...,  0.56630969,
        0.21883607,  0.00977684])

In [808]:
np.array(seqs).shape

(62, 30, 1662)

In [809]:
X_data = np.array(seqs)

In [810]:
X_data.shape

(62, 30, 1662)

In [811]:
labels

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61]

In [812]:
# changing the labels from 0,1,2 to categorical data for easier accessebility
Y_label = to_categorical(labels).astype(int)
Y_label

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [813]:
Y_label.shape

(62, 62)

In [814]:
# splitting
X_train, X_test, Y_train, Y_test = train_test_split(X_data, Y_label, test_size=0.3)
X_test.shape

(19, 30, 1662)

### Building LSTM

In [815]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [816]:
# adding the logs folder
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [817]:
# neural network

model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30,1662)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))

# adding 64 units for dense layer
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

c:\Users\araya\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [818]:
# eg
eg_res = [.7, 0.2, 0.1]
actions[np.argmax(eg_res)]

'กฎกระทรวง.mp4'

In [819]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [820]:
model.fit(X_train, Y_train, epochs=300, callbacks=[tb_callback])
# tensorboard --logdir=.

Epoch 1/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 5s 76ms/step - categorical_accuracy: 0.0000e+00 - loss: 4.1605
Epoch 2/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - categorical_accuracy: 0.0155 - loss: 17.4790  
Epoch 3/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - categorical_accuracy: 0.0259 - loss: 5.6571
Epoch 4/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - categorical_accuracy: 0.0518 - loss: 4.1316 
Epoch 5/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - categorical_accuracy: 0.0259 - loss: 4.2661
Epoch 6/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - categorical_accuracy: 0.0259 - loss: 4.4333
Epoch 7/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - categorical_accuracy: 0.0000e+00 - loss: 4.3245
Epoch 8/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - categorical_accuracy: 0.0155 - loss: 4.1519    
Epoch 9/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - categorical_accuracy: 0.0259 - loss: 4.2284
Epoch 10/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - categorical_accuracy: 0.0155 - loss: 4.1265    
Epoch 11/300
2/2 ━━

In [821]:
model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_48 (LSTM)                  │ (None, 30, 64)         │       442,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_49 (LSTM)                  │ (None, 30, 128)        │        98,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_50 (LSTM)                  │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_49 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_50 (Dense)                │ (None, 62)             │         2,046 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,795,868 (6.85 MB)

 Trainable params: 598,622 (2.28 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,197,246 (4.57 MB)

In [822]:
res=model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 351ms/step


In [833]:
# again the actions with the max value provided by softmax is returned
actions[np.argmax(res[4])]

'เสรีภาพ.mp4'

In [834]:
actions[np.argmax(Y_test[4])]

'กระโดด.mp4'

In [825]:
res[0]

array([6.3614169e-10, 3.0754967e-12, 2.0070323e-12, 2.1532799e-24,
       2.1561692e-20, 1.7584062e-26, 1.2675041e-01, 1.7304397e-09,
       4.4307029e-07, 1.8685256e-10, 2.5035581e-12, 3.3671555e-14,
       1.4661473e-02, 4.7236715e-33, 8.5786980e-01, 3.1077927e-16,
       4.1084547e-04, 1.7123599e-08, 4.5735862e-28, 1.0999481e-07,
       6.9791474e-07, 7.5544902e-24, 2.0473088e-04, 2.5380922e-10,
       1.3093950e-20, 4.2368713e-11, 4.1878586e-05, 2.9478992e-06,
       5.2299626e-11, 8.7867194e-18, 1.2265722e-12, 1.5006026e-23,
       4.5834929e-07, 3.5660457e-20, 3.3237083e-10, 1.5653501e-14,
       8.4509399e-11, 4.2719859e-29, 3.2512336e-13, 2.4185783e-32,
       4.3881471e-05, 2.6073999e-07, 6.6510985e-14, 3.1582798e-13,
       1.4811833e-08, 1.6452044e-10, 1.2757273e-24, 3.3762517e-20,
       2.3390094e-27, 8.3827112e-11, 1.2340488e-08, 6.0356321e-18,
       1.7330809e-18, 5.0725322e-12, 7.4164032e-24, 2.3928138e-21,
       1.0240447e-15, 1.2674446e-09, 1.1723580e-05, 1.2631021e

In [835]:
Y_test[0]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Evaluate

In [836]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [837]:
Y_hat = model.predict(X_train)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step 


In [838]:
Y_true = np.argmax(Y_train, axis=1).tolist()
# one hot encoding
Y_hat = np.argmax(Y_hat, axis=1).tolist()

In [839]:
Y_hat

[7,
 14,
 10,
 45,
 26,
 22,
 36,
 17,
 10,
 15,
 58,
 6,
 30,
 11,
 11,
 25,
 56,
 32,
 0,
 38,
 27,
 8,
 28,
 61,
 34,
 11,
 41,
 11,
 57,
 12,
 27,
 44,
 16,
 1,
 53,
 19,
 43,
 11,
 20,
 40,
 51,
 49,
 23]

In [840]:
# confution matrix
multilabel_confusion_matrix(Y_true, Y_hat)

array([[[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 1,  0]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 1,  0]],

       [[40,  2],
        [ 1,  0]],

       [[38,  4],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[41,  1],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 1,  0]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,  0],
        [ 0,  1]],

       [[42,

In [841]:
accuracy_score(Y_true, Y_hat)

0.8372093023255814