### Tensor Initialization

In [17]:
import torch

In [18]:
print(torch.__version__)

2.1.0+cpu


In [19]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [20]:
my_tensor.dtype

torch.float32

In [21]:
my_tensor.device

device(type='cpu')

In [22]:
my_tensor.shape

torch.Size([2, 3])

In [23]:
x = torch.empty(size=(3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
x = torch.zeros((3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
x = torch.rand((3, 3))
x

tensor([[0.3716, 0.6712, 0.4955],
        [0.0697, 0.3813, 0.9849],
        [0.7228, 0.0763, 0.1868]])

In [27]:
x = torch.ones((3, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
x = torch.eye(5, 5) #Indentity , eye
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
x = torch.arange(start=0, end=5, step=1)
x

tensor([0, 1, 2, 3, 4])

In [32]:
x = torch.linspace(start=0.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [37]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x

tensor([[ 0.8255, -1.6807, -2.5292,  1.5716, -0.2918]])

In [38]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Converting between tensor types

In [40]:
#Convert tensors to other types (int, float, double)
tensor = torch.arange(4)
tensor.bool()

tensor([False,  True,  True,  True])

In [41]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [43]:
tensor.long()

tensor([0, 1, 2, 3])

In [44]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [45]:
tensor.float()

tensor([0., 1., 2., 3.])

In [46]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [47]:
# Array to tensor coversion and tensor to array
import numpy as np 

In [51]:
np_array = np.zeros((5, 5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [53]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])