### Tensor Initialization

In [97]:
import torch

In [98]:
print(torch.__version__)

2.1.0+cpu


In [99]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [100]:
my_tensor.dtype

torch.float32

In [101]:
my_tensor.device

device(type='cpu')

In [102]:
my_tensor.shape

torch.Size([2, 3])

In [103]:
x = torch.empty(size=(3, 3))
x

tensor([[0.7200, 0.0822, 0.6082],
        [0.5806, 0.4929, 0.2725],
        [0.7963, 0.3315, 0.4065]])

In [104]:
x = torch.zeros((3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [105]:
x = torch.rand((3, 3))
x

tensor([[0.0699, 0.6067, 0.0628],
        [0.1692, 0.1373, 0.5797],
        [0.2503, 0.7388, 0.4318]])

In [106]:
x = torch.ones((3, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [107]:
x = torch.eye(5, 5) #Indentity , eye
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [108]:
x = torch.arange(start=0, end=5, step=1)
x

tensor([0, 1, 2, 3, 4])

In [109]:
x = torch.linspace(start=0.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [110]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x

tensor([[ 1.2916, -0.7012,  0.4059, -0.0869,  0.9410]])

In [111]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Converting between tensor types

In [112]:
#Convert tensors to other types (int, float, double)
tensor = torch.arange(4)
tensor.bool()

tensor([False,  True,  True,  True])

In [113]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [114]:
tensor.long()

tensor([0, 1, 2, 3])

In [115]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [116]:
tensor.float()

tensor([0., 1., 2., 3.])

In [117]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [118]:
# Array to tensor coversion and tensor to array
import numpy as np 

In [119]:
np_array = np.zeros((5, 5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [120]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [121]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Tensor Math

In [122]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

In [123]:
#การบวก
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [124]:
z2 = torch.add(x, y)
z = x + y
z

tensor([10, 10, 10])

In [125]:
#การลบ
z = x - y
z

tensor([-8, -6, -4])

In [126]:
#การหาร
z = torch.true_divide(x, y)
z

tensor([0.1111, 0.2500, 0.4286])

In [127]:
#Inplace operation
t = torch.zeros(3)
t.add_(x)
t += x # t = t + x
t

tensor([2., 4., 6.])

In [128]:
#Exponentiation
z = x.pow(2)
z

tensor([1, 4, 9])

In [129]:
z = x ** 2
z

tensor([1, 4, 9])

In [130]:
#simple comparison
z = x > 0
z

tensor([True, True, True])

In [131]:
z = x < 0
z

tensor([False, False, False])

In [132]:
#การคูณ Matrix
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # 2x3
x3 = x1.mm(x2)

In [133]:
#martrix exponentiation
matrix_exp = torch.rand(5, 5)
matrix_exp.matrix_power(3)

tensor([[3.3870, 4.5620, 3.1488, 2.8988, 2.9252],
        [2.0708, 2.4688, 2.3925, 1.6651, 2.0373],
        [2.9284, 3.3617, 2.6208, 1.9456, 2.7937],
        [2.6117, 2.9680, 2.5875, 1.9120, 2.4156],
        [3.1940, 4.1327, 3.0637, 2.6083, 2.8742]])

In [134]:
#element wise multiplication
z = x * y
z

tensor([ 9, 16, 21])

In [135]:
# dot product
z = torch.dot(x, y)
z

tensor(46)

In [136]:
9+16+21

46

In [137]:
# batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
out_bmm

tensor([[[5.8654, 5.0032, 4.4680,  ..., 4.9166, 5.2838, 4.6641],
         [6.2475, 4.7404, 3.6560,  ..., 4.6118, 5.1386, 4.6508],
         [4.4859, 3.1814, 4.0617,  ..., 4.1735, 4.2798, 4.4701],
         ...,
         [4.9875, 4.1316, 3.7520,  ..., 4.1095, 4.7537, 4.2067],
         [5.7484, 4.8061, 4.7276,  ..., 4.2244, 5.9036, 5.3003],
         [4.8777, 4.0141, 3.7333,  ..., 4.1213, 4.6625, 4.0465]],

        [[5.1808, 4.6691, 4.3853,  ..., 4.2949, 6.2205, 4.9554],
         [4.4106, 3.2015, 4.3290,  ..., 3.3077, 5.4739, 4.1161],
         [5.0914, 4.1182, 5.1905,  ..., 4.3343, 6.7110, 5.9723],
         ...,
         [4.0808, 3.2386, 4.6115,  ..., 3.9229, 5.4366, 5.1274],
         [6.1514, 4.9408, 5.8876,  ..., 4.6461, 7.6818, 6.3762],
         [4.8563, 3.2611, 5.7090,  ..., 4.0415, 6.1250, 5.1531]],

        [[4.2970, 4.4962, 4.7012,  ..., 4.6939, 3.4016, 5.9829],
         [5.9825, 4.8084, 3.7722,  ..., 4.3882, 3.7259, 5.9176],
         [4.6369, 4.6431, 3.6678,  ..., 4.3600, 3.9698, 5.

### Useful tensor operation

In [138]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

In [139]:
sum_x = torch.sum(x, dim=0)
sum_x

tensor(6)

In [140]:
values, indices = torch.min(x, dim=0)

In [141]:
values, indices = torch.max(x, dim=0)

In [142]:
abs_x = torch.abs(x)
abs_x

tensor([1, 2, 3])

In [143]:
z = torch.argmin(x, dim=0)
z

tensor(0)

In [144]:
z = torch.argmax(x, dim=0)
z

tensor(2)

In [145]:
mean_x = torch.mean(x.float(), dim=0)
mean_x

tensor(2.)

In [146]:
z = torch.eq(x, y)
torch.sort(y, dim=0, descending=False)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))

### Tensor Indexing

In [147]:
batch_size = 10
feature = 25
x = torch.rand((batch_size, feature))
x[0].shape

torch.Size([25])

In [148]:
x[:, 0].shape

torch.Size([10])

In [149]:
x[2,0:10] # 0:10 ---> [0, 1, 2, ..., 9]

tensor([0.0478, 0.8409, 0.1776, 0.9285, 0.6717, 0.9178, 0.8108, 0.5190, 0.1122,
        0.8784])

In [150]:
x = torch.arange(10)
indices = [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [151]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
x[rows, cols]

tensor([0.5362, 0.8449])

In [152]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])