### Artificial Neuron / Perceptron
สร้าง AND Gate ด้วย Neuron (Perceptron) ด้วย Scikit-learn

In [1]:
import numpy as np 

X = [[0, 0],
    [0, 1],
    [1, 0],
    [1, 1]]

X_train = np.array(X)

y = [0, 0, 0, 1] # target (y) for AND gate
#y = [0,1,1,1] # OR gate
#y = [0,1,1,0] # XOR
y_train = np.array(y)

### Train

In [15]:
from sklearn.linear_model import Perceptron

# model = Perceptron(random_state=0, verbose=False)
model = Perceptron(random_state=0, verbose=True)
# model = Perceptron()

model.fit(X_train, y_train)

-- Epoch 1
Norm: 0.00, NNZs: 0, Bias: -1.000000, T: 4, Avg. loss: 0.750000
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 1.41, NNZs: 2, Bias: 0.000000, T: 8, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.00, NNZs: 0, Bias: -2.000000, T: 12, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 1.41, NNZs: 2, Bias: -1.000000, T: 16, Avg. loss: 0.500000
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 1.00, NNZs: 1, Bias: -2.000000, T: 20, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 2.24, NNZs: 2, Bias: -1.000000, T: 24, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 1.00, NNZs: 1, Bias: -3.000000, T: 28, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 2.24, NNZs: 2, Bias: -2.000000, T: 32, Avg. loss: 0.500000
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 1.41, NNZs: 2, Bias: -3.000000, T: 36, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- E

Perceptron(verbose=True)

### Evaluate

In [3]:
print('score: ', model.score(X_train, y_train))
print('predicted: ', model.predict(X_train))
print('target: ', np.array(y))

score:  1.0
predicted:  [0 0 0 1]
target:  [0 0 0 1]


### Weight and bias

In [4]:
print('weight [w1 w2] =', model.coef_[0])
print('w0 (bias) =', model.intercept_[0])

weight [w1 w2] = [2. 2.]
w0 (bias) = -2.0


### Predict

In [5]:
X_train

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [6]:
x_new = X_train

model.predict(x_new)

array([0, 0, 0, 1])

In [10]:
X_new = ([[0, 1]])

model.predict(X_new)

array([0])

In [11]:
X_new = ([[1, 1]])

model.predict(X_new)

array([1])

In [13]:
X_new = ([[0, 1],
        [1, 1]])

model.predict(X_new)

array([0, 1])

### Perceptron ด้วย Python ไม่ใช้ Library (Scratch Code)

In [14]:
def and_gate(x1, x2):
    w0 = -2 #bias
    w1 = 2
    w2 = 2

    threshold = 0.0

    s = w0 + (w1 * x1) + (w2 * x2)

    if s> threshold:
        result = 1
    else:
        result = 0

    print('output y={} [s={:.2f}]'.format(result, s))

and_gate(0,0)
and_gate(0,1)
and_gate(1,0)
and_gate(1,1)

output y=0 [s=-2.00]
output y=0 [s=0.00]
output y=0 [s=0.00]
output y=1 [s=2.00]


### XOR
สร้าง XOR Gate ด้วย Neuron (Perceptron) ด้วย scikit-learn

In [16]:
import numpy as np 

X = [[0,0],
    [0,1],
    [1,0],
    [1,1]]

X_train = np.array(X)

# y = [0,0,0,1]
# y = [0,1,1,1]
y = [0,1,1,0]
y_train = np.array(y)

In [17]:
from sklearn.linear_model import Perceptron

# model = Perceptron(random_state=0, verbose=False)
model = Perceptron(random_state=0, verbose=True)
# model = Perceptron()

model.fit(X_train, y_train)

-- Epoch 1
Norm: 0.00, NNZs: 0, Bias: 0.000000, T: 4, Avg. loss: 1.000000
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.00, NNZs: 0, Bias: 0.000000, T: 8, Avg. loss: 1.000000
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.00, NNZs: 0, Bias: 0.000000, T: 12, Avg. loss: 1.000000
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.00, NNZs: 0, Bias: 0.000000, T: 16, Avg. loss: 1.000000
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.00, NNZs: 0, Bias: 0.000000, T: 20, Avg. loss: 1.000000
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.00, NNZs: 0, Bias: 0.000000, T: 24, Avg. loss: 1.000000
Total training time: 0.00 seconds.
Convergence after 6 epochs took 0.00 seconds


Perceptron(verbose=True)

### Evaluate

In [18]:
print('score: ', model.score(X_train, y_train))
print('predicted: ', model.predict(X_train))
print('target: ', np.array(y))

score:  0.5
predicted:  [0 0 0 0]
target:  [0 1 1 0]


### OR Gate

In [19]:
import numpy as np 

X = [[0, 0],
    [0, 1],
    [1, 0],
    [1, 1]]

X_train = np.array(X)

y = [0, 0, 0, 1] # target (y) for AND gate
y = [0,1,1,1] # OR gate
#y = [0,1,1,0] # XOR
y_train = np.array(y)

### Train

In [20]:
from sklearn.linear_model import Perceptron

# model = Perceptron(random_state=0, verbose=False)
model = Perceptron(random_state=0, verbose=True)
# model = Perceptron()

model.fit(X_train, y_train)

-- Epoch 1
Norm: 1.41, NNZs: 2, Bias: 0.000000, T: 4, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 2.24, NNZs: 2, Bias: 0.000000, T: 8, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 2.24, NNZs: 2, Bias: -1.000000, T: 12, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 2.83, NNZs: 2, Bias: 0.000000, T: 16, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 2.83, NNZs: 2, Bias: -1.000000, T: 20, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 2.83, NNZs: 2, Bias: -1.000000, T: 24, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 2.83, NNZs: 2, Bias: -1.000000, T: 28, Avg. loss: 0.000000
Total training time: 0.00 seconds.
Convergence after 7 epochs took 0.00 seconds


Perceptron(verbose=True)