### List VS Array      

Array จะเก็บข้อมูลที่มี datatype ที่เหมือนกัน        
list สามารถเก็บ datatype ได้หลายๆอย่างไว้ด้วยกัน       

In [1]:
import numpy as np

In [6]:
arr = np.array(5)
arr

array(5)

In [7]:
arr.ndim

0

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a.ndim

1

### Array ที่มีมากกว่า 1 มิติ        

การสร้าง array 2 มิติ จะต้องมี [] คลุมอีกชั้นแล้วคั่นด้วย comma     ***ชึ่งเราจะนับเป็นแถวๆไป

In [9]:
a = np.array([[1,2,3],[4,5,6]])  #It has two group of brackets.
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.ndim

2

In [13]:
b = np.array([[[1,2,3],[4,5,6]]])
b

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
b.ndim

3

### การเข้าถึงสมาชิกภายใน Array (Index)

In [15]:
import numpy as np

In [16]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [18]:
a.ndim

1

In [19]:
print(a)

[1 2 3 4 5]


In [20]:
print(a[4])

5


### การเข้าถึงสมาชิกใน Array 2 มิติ      

เราสามารถเข้าถึงสมาชิกแต่ละตัวได้โดยการระบุ เลขแถวก่อน แล้วตามด้วย เลขหลัก      

นอกจากนี้เรายังสามารถเปลี่ยนสมาชิกใน array ได้อีกด้วย       


In [25]:
import numpy as np

In [26]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
print(a[1][0])
print(a[2][1])

3
6


In [28]:
a[1][0] = 65

In [29]:
print(a)

[[ 1  2]
 [65  4]
 [ 5  6]]


### Array 3 มิติ    

เป็นการนำ Array 2 มิติ เข้ามาซ้อนกัน
เราสามารถเข้าถึง Array 3 มิติ ได้โดย [dept][row][column]

In [30]:
import numpy as np

In [31]:
a = np.array([[[1,2,3],[4,5,6]]])

In [32]:
a.ndim

3

In [33]:
print(a[0][1][1])
print(a[0][0][2])

5
3


In [34]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [35]:
print(b[1][0][1])

8


### Datatype         
1. Integer     
2. Float     
3. String     
4. Boolean      
5. Complex      
6. Object      

In [36]:
import numpy as np

In [37]:
a = np.array([1,2,3,4,5])
a.dtype

dtype('int64')

In [38]:
a = np.array([1,2,3,4,5],dtype=int)
a.dtype

dtype('int64')

In [40]:
a = np.array([1,2,3,4,5],dtype=float)
a.dtype

dtype('float64')

In [41]:
a

array([1., 2., 3., 4., 5.])

In [42]:
a = np.array([1,2,3,4,5],dtype=complex)

In [43]:
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

### Matrix     

สำหรับ Data Science    

Type of Matrix   
1. Squere Matrix คือ จำนวนแถว และ คอลัมน์ เท่ากัน      
2. Zero Matrix คือ สมาชิกทุกตัวในเมทริกซ์เป็น 0 ทั้งหมด **สามารถเอาไปใช้กับ image processing        
3. Identity Matrix คือ สมาชิกเส้นทแยงมุมมีค่าเป็น 1 ..... ส่วนที่เหลือเป็น 0       

In [44]:
import numpy as np

In [45]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [46]:
a = np.zeros(5,dtype=int)
a

array([0, 0, 0, 0, 0])

In [47]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [48]:
c = np.zeros([3,4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
d = np.zeros([3,4], dtype = int) #Squere Matrix
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Ones Matrix

In [50]:
import numpy as np

In [51]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
a = np.ones(10, dtype=int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
b = np.ones((3,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### เราสามารถกำหนดค่าคงที่ใดๆให้ Array ได้    
โดยใช้ np.full()    

In [54]:
c = np.full(5,10)
c

array([10, 10, 10, 10, 10])

In [56]:
d = np.full((3,3),7) #สร้างArray (3,3) โดยเลขทุกตัวเป็น 7
d

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### Empty    


In [57]:
import numpy as np

In [62]:
np.empty((3,4))  #สุ่มค่า

array([[6.95270674e-310, 9.27812437e-312, 0.00000000e+000,
        9.27812437e-312],
       [1.89146896e-307, 9.27812437e-312, 7.17355477e-091,
        0.00000000e+000],
       [9.27812437e-312, 9.27812437e-312, 9.27812437e-312,
        0.00000000e+000]])

### Identity   
Identity Matrix จะเป็น Squere Matrix เสมอ     

In [63]:
import numpy as np

In [64]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [69]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [67]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### Linspace    
คือ การกำหนดช่วงโดยเว้นระยะที่เท่าๆกัน     
np.linspace(start, stop, number)     

In [117]:
import numpy as np

In [120]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [121]:
np.linspace(1, 5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [122]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [124]:
np.linspace(1, 5, endpoint=False) #ไม่เอาตัวสุดท้าย

array([1.  , 1.08, 1.16, 1.24, 1.32, 1.4 , 1.48, 1.56, 1.64, 1.72, 1.8 ,
       1.88, 1.96, 2.04, 2.12, 2.2 , 2.28, 2.36, 2.44, 2.52, 2.6 , 2.68,
       2.76, 2.84, 2.92, 3.  , 3.08, 3.16, 3.24, 3.32, 3.4 , 3.48, 3.56,
       3.64, 3.72, 3.8 , 3.88, 3.96, 4.04, 4.12, 4.2 , 4.28, 4.36, 4.44,
       4.52, 4.6 , 4.68, 4.76, 4.84, 4.92])

### Arange     
np.arange(start, stop, step, dtype)     

In [125]:
import numpy as np

In [129]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [132]:
np.arange(-5,6)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [131]:
np.arange(1, 10, 2, dtype=int)

array([1, 3, 5, 7, 9])

### Random    
เป็นการสุ่มตัวเลขตั้งแต่ 0 - ก่อน1

In [133]:
import numpy as np

In [138]:
np.random.random((2,2))

array([[0.7636528 , 0.07590542],
       [0.48919996, 0.87637134]])

In [139]:
np.random.random((10,10))

array([[0.82570833, 0.17637952, 0.78262455, 0.74236779, 0.39036703,
        0.94819117, 0.56153562, 0.96001646, 0.57978046, 0.70650473],
       [0.44142211, 0.25306493, 0.14006644, 0.02814188, 0.26601412,
        0.22953702, 0.47366399, 0.5888094 , 0.8717809 , 0.23391492],
       [0.20874095, 0.19058923, 0.53100939, 0.12820787, 0.09128388,
        0.29094104, 0.03548088, 0.40667145, 0.63219109, 0.2735456 ],
       [0.70392722, 0.72922225, 0.20545859, 0.01110041, 0.38317998,
        0.10200135, 0.34831477, 0.9590325 , 0.11866446, 0.90239353],
       [0.26275338, 0.07970699, 0.98684376, 0.23863466, 0.9203895 ,
        0.10236774, 0.48576188, 0.22692624, 0.01477323, 0.98445694],
       [0.56575856, 0.73677821, 0.82412673, 0.51954763, 0.67492662,
        0.84986475, 0.7648729 , 0.58897199, 0.83615433, 0.06778817],
       [0.55434105, 0.63723307, 0.75844455, 0.13635705, 0.70677915,
        0.79376217, 0.15006427, 0.6670818 , 0.90426157, 0.0448974 ],
       [0.45442099, 0.69624286, 0.9311647

### Numpy Attribute

In [140]:
import numpy as np

In [144]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [145]:
a.shape

(5,)

In [146]:
b.shape

(3, 3)

In [147]:
a.size

5

In [148]:
b.size

9

In [150]:
a.dtype

dtype('int64')

In [151]:
a.itemsize   #หน่วย คือ byte

8

### Slice Array    
เราสามารถระบุค่าของสมาชิกแล้วทำการ slice ได้

In [152]:
import numpy as np

In [179]:
a = np.arange(1,11)
b = np.array([20,10,30,50,40])
print(a)
print(a[2])

[ 1  2  3  4  5  6  7  8  9 10]
3


In [169]:
a[:] #ตำแหน่งท้ายไม่นับ

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
a[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [171]:
a[7:]

array([ 8,  9, 10])

In [172]:
a[:5] #นับตั้งแต่สมาชิกตัวแรกไปจนถึงก่อนตัวสุดท้าย 1 ตัว

array([1, 2, 3, 4, 5])

In [173]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [175]:
b[1:]  #เริ่มตั้งแต่ index = 1 ไปจนถึงตัวสุดท้าย

array([10, 30, 50, 40])

In [176]:
b[3:]

array([50, 40])

In [177]:
b[:2]

array([20, 10])

### Slice Array 2 มิติ    
x[start:stop:step,start:stop:step]

x[  :   ,   :  ]

In [180]:
import numpy as np

In [181]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
x[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

In [184]:
x[1:,0:]

array([[4, 5, 6],
       [7, 8, 9]])

In [185]:
x[:,2:]

array([[3],
       [6],
       [9]])

### Example of usage

In [77]:
import numpy as np

arr = np.array(1)
print(arr)


1


In [78]:
arr.ndim

0

In [83]:
a = np.array([1,2,3,4,5])
print(a)
print(f'Dimension of a = {a.ndim}')

[1 2 3 4 5]
Dimension of a = 1


In [84]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
b.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [86]:
c = np.zeros(10)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [89]:
d = np.zeros((6,5),dtype=int)
d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [93]:
d = np.ones(10,dtype=int)
d

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [95]:
d = np.ones((5,6),dtype=float)
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [109]:
d = np.identity(10)
d

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [107]:
x = np.eye(5,4,dtype=int)
x

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [111]:
x = np.eye(5,k=1,dtype=int)
x

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [116]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)

[ 4 10 18]
