In [46]:
import torch
import numpy as np 

In [47]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [48]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [49]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [50]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [51]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.6086, 0.7564],
        [0.5430, 0.8032]])

In [52]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor :  {rand_tensor}")
print(f"Ones Tensor :  {ones_tensor}")
print(f"Zeros Tensor : {zeros_tensor}")

Random Tensor :  tensor([[0.8041, 0.2538, 0.5359],
        [0.0851, 0.9693, 0.9442]])
Ones Tensor :  tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor : tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [53]:
tensor = torch.rand(3,4)
tensor

tensor([[0.8841, 0.9495, 0.7142, 0.6591],
        [0.3456, 0.9011, 0.1540, 0.8750],
        [0.6586, 0.3784, 0.7762, 0.0269]])

In [54]:
# if torch.cuda.is_available():
#     tensor = tensor.to('cuda')

In [55]:
torch.cuda.is_available()

False

In [56]:
tensor = torch.ones(4,4)
print('First row : ', tensor[0])
print('First column : ', tensor[:,0])
print('Last column : ', tensor[...,-1])
tensor[:,1] = 0
print(tensor)

First row :  tensor([1., 1., 1., 1.])
First column :  tensor([1., 1., 1., 1.])
Last column :  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [57]:
tensor[0]

tensor([1., 0., 1., 1.])

In [59]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [62]:
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [63]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [69]:
y3 = torch.rand_like(tensor) # random ตั้งแต่ 0 ถึง 1
y3

tensor([[0.0552, 0.8430, 0.8852, 0.3477],
        [0.6020, 0.9684, 0.3941, 0.6151],
        [0.2662, 0.2386, 0.7459, 0.8129],
        [0.8105, 0.1489, 0.7002, 0.4571]])

In [71]:
torch.matmul(tensor, tensor.T, out=y3)
y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [72]:
z1 = tensor * tensor
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [73]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [74]:
agg = tensor.sum()
agg

tensor(12.)

In [76]:
tensor.add(5) #บวก 5 ทุกตำแหน่ง

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])