In [81]:
import torch
import numpy as np 

In [82]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [83]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [84]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [85]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [86]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.8201, 0.0675],
        [0.8226, 0.5269]])

In [87]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor :  {rand_tensor}")
print(f"Ones Tensor :  {ones_tensor}")
print(f"Zeros Tensor : {zeros_tensor}")

Random Tensor :  tensor([[0.6411, 0.0442, 0.6557],
        [0.8887, 0.8048, 0.6286]])
Ones Tensor :  tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor : tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [88]:
tensor = torch.rand(3,4)
tensor

tensor([[0.2655, 0.7140, 0.3461, 0.7160],
        [0.9258, 0.8386, 0.4592, 0.5552],
        [0.7071, 0.1346, 0.2947, 0.7677]])

In [89]:
# if torch.cuda.is_available():
#     tensor = tensor.to('cuda')

In [90]:
torch.cuda.is_available()

False

In [91]:
tensor = torch.ones(4,4)
print('First row : ', tensor[0])
print('First column : ', tensor[:,0])
print('Last column : ', tensor[...,-1])
tensor[:,1] = 0
print(tensor)

First row :  tensor([1., 1., 1., 1.])
First column :  tensor([1., 1., 1., 1.])
Last column :  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [92]:
tensor[0]

tensor([1., 0., 1., 1.])

In [93]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [94]:
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [95]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [96]:
y3 = torch.rand_like(tensor) # random ตั้งแต่ 0 ถึง 1
y3

tensor([[0.0991, 0.4048, 0.1553, 0.9028],
        [0.7951, 0.6613, 0.3171, 0.7657],
        [0.3036, 0.2197, 0.4625, 0.0512],
        [0.0428, 0.0152, 0.2120, 0.8081]])

In [97]:
torch.matmul(tensor, tensor.T, out=y3)
y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [98]:
z1 = tensor * tensor
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [99]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [100]:
agg = tensor.sum()
agg

tensor(12.)

In [101]:
tensor.add_(5) #บวก 5 ทุกตำแหน่ง

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])