### Two datasets prediction

In [151]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [152]:
df = pd.read_csv('coor_test.csv')

In [153]:
df

file_name frame_number          landmark            x            y  \
0     กว๊านพะเยา            0              NOSE  0.506505728   0.25162822   
1     กว๊านพะเยา            0    LEFT_EYE_INNER  0.541825712  0.209687233   
2     กว๊านพะเยา            0          LEFT_EYE  0.560136259  0.211288571   
3     กว๊านพะเยา            0    LEFT_EYE_OUTER  0.580134988  0.213384986   
4     กว๊านพะเยา            0   RIGHT_EYE_INNER  0.474366099  0.208439469   
...          ...          ...               ...          ...          ...   
6530     กระท่อม           98       RIGHT_ANKLE  0.357209593  2.286435843   
6531     กระท่อม           98         LEFT_HEEL   0.65984118  2.359816074   
6532     กระท่อม           98        RIGHT_HEEL  0.357456833  2.362872362   
6533     กระท่อม           98   LEFT_FOOT_INDEX  0.612463713  2.443391562   
6534     กระท่อม           98  RIGHT_FOOT_INDEX  0.397871345  2.435553074   

                 z  
0     -1.337439299  
1     -1.262086272  
2     -1.262583017  
3     -1.262981415  
4     -1.262893319  
...            ...  
6530   0.496406108  
6531   0.808552027  
6532   0.528459191  
6533   0.074209623  
6534  -0.264272988  

[6535 rows x 6 columns]

In [154]:
X = df.drop('file_name', axis=1)
X = X.drop('frame_number', axis=1)
X = X.drop('landmark', axis=1)
X

x            y             z
0     0.506505728   0.25162822  -1.337439299
1     0.541825712  0.209687233  -1.262086272
2     0.560136259  0.211288571  -1.262583017
3     0.580134988  0.213384986  -1.262981415
4     0.474366099  0.208439469  -1.262893319
...           ...          ...           ...
6530  0.357209593  2.286435843   0.496406108
6531   0.65984118  2.359816074   0.808552027
6532  0.357456833  2.362872362   0.528459191
6533  0.612463713  2.443391562   0.074209623
6534  0.397871345  2.435553074  -0.264272988

[6535 rows x 3 columns]

In [155]:
type(X.x[0])

str

In [156]:
X.x = pd.to_numeric(X.x, errors='coerce')
X.y = pd.to_numeric(X.y, errors='coerce')
X.z = pd.to_numeric(X.z, errors='coerce')

In [157]:
type(X.x[0])

numpy.float64

In [158]:
X.isnull().sum()

x    1
y    1
z    1
dtype: int64

In [159]:
X.fillna(X.median(numeric_only=True).round(1), inplace=True)

In [160]:
X.isnull().sum()

x    0
y    0
z    0
dtype: int64

In [161]:
y = df.file_name
y

0       กว๊านพะเยา
1       กว๊านพะเยา
2       กว๊านพะเยา
3       กว๊านพะเยา
4       กว๊านพะเยา
           ...    
6530       กระท่อม
6531       กระท่อม
6532       กระท่อม
6533       กระท่อม
6534       กระท่อม
Name: file_name, Length: 6535, dtype: object

### Feature Scaling

In [162]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 

X_sc = sc.fit_transform(X)
X_sc

array([[ 0.04031865, -0.97468495, -0.59857823],
       [ 0.24299295, -1.0334603 , -0.51045511],
       [ 0.34806313, -1.03121622, -0.51103604],
       ...,
       [-0.81495861,  1.9839751 ,  1.58353457],
       [ 0.64833024,  2.09681328,  1.05230321],
       [-0.58305073,  2.08582856,  0.65645786]])

### Train-Test-Spilt

In [163]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X_sc, y, test_size=0.3, random_state=42)

In [164]:
X_train

array([[-2.51769728, -0.10904899, -0.06244516],
       [ 2.26436128, -0.08997174, -0.05291407],
       [-0.19638255, -0.97099259, -0.39530758],
       ...,
       [ 1.3093626 , -0.61037244,  0.67196215],
       [-0.23351983, -0.83253218, -0.22397936],
       [ 0.28627967, -1.00129285, -0.49559814]])

In [165]:
y_train

4734       กระท่อม
5228       กระท่อม
5186       กระท่อม
387     กว๊านพะเยา
2004    กว๊านพะเยา
           ...    
3772       กระท่อม
5191       กระท่อม
5226       กระท่อม
5390       กระท่อม
860     กว๊านพะเยา
Name: file_name, Length: 4574, dtype: object

### Model

In [173]:
from sklearn.neural_network import MLPClassifier 

model = MLPClassifier(hidden_layer_sizes=(10000), random_state=1, verbose=True, max_iter=500)

model.fit(X_train, y_train)


Iteration 1, loss = 0.76197884
Iteration 2, loss = 0.70009492
Iteration 3, loss = 0.69773477
Iteration 4, loss = 0.69966631
Iteration 5, loss = 0.70220908
Iteration 6, loss = 0.69855569
Iteration 7, loss = 0.69703317
Iteration 8, loss = 0.69736926
Iteration 9, loss = 0.70127244
Iteration 10, loss = 0.69871334
Iteration 11, loss = 0.69694644
Iteration 12, loss = 0.69597062
Iteration 13, loss = 0.69703750
Iteration 14, loss = 0.69737330
Iteration 15, loss = 0.69895807
Iteration 16, loss = 0.69637289
Iteration 17, loss = 0.69701165
Iteration 18, loss = 0.69613710
Iteration 19, loss = 0.69631992
Iteration 20, loss = 0.69645799
Iteration 21, loss = 0.69619801
Iteration 22, loss = 0.69629584
Iteration 23, loss = 0.69625113
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.


MLPClassifier(hidden_layer_sizes=10000, max_iter=500, random_state=1,
              verbose=True)

In [167]:
X.sample()

x        y         z
4945  0.687411  2.06669  0.679956

In [179]:
X_input = [[	0.74947232, 0.563502729, -0.456387341]]
X_input = sc.transform(X_input)
X_input = np.array(X_input)
X_input.reshape(-1,1)

c:\Users\araya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 1.43451753],
       [-0.53762955],
       [ 0.43178584]])

In [180]:
model.predict(X_input)

array(['กว๊านพะเยา'], dtype='<U10')

In [181]:
model.score(X_train, y_train)

0.5139921294271972